### ISSUE TITLE
为什么我的反代站会突然转到ao3的官网去

### ISSUE THREAD

**Issue by PigeonHouse99** [ExcitedCodes/URLOfOurOwn#2]
![QQ截图20200310181658](https://user-images.githubusercontent.com/54053004/76302777-88396e80-62fb-11ea-8c0c-073a1a518352.png)
![QQ截图20200310181712](https://user-images.githubusercontent.com/54053004/76302778-8a033200-62fb-11ea-8b89-a786ada0f4ce.png)

**Comment by PigeonHouse99** [comment]
纯小白，不知道怎么设置这个，我点开一篇成人限制的就会这样，直接转去ao3的官网了

**Comment by ExcitedCodes** [comment]
HTTP Location没处理好, 已经修复了, 请更换最新conf

**Comment by PigeonHouse99** [comment]
辛苦了！十分感谢！话说这个问题属于nginx的跨域问题吗？因为我发现图二中的ao3官网前面写的是http不是https，协议不同

**Comment by ExcitedCodes** [comment]
个人倾向于认为这是 AO3 的设计问题, 因为我们 proxy_pass 时走的已经是 https:// 了

**Comment by PigeonHouse99** [comment]
soga~，谢谢了！
