### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by Hakuba64** [ExcitedCodes/URLOfOurOwn#4]
proxy_cache 是否需要设置 max_size?

**Comment by ExcitedCodes** [comment]
这要根据你的需求来判断. 我们不建议在 Nginx 上设置缓存, 这会导致登录用户的信息外泄等问题. 如果你一定要设置, 请参阅 [官方文档](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path)
