### ISSUE TITLE
备用站点提交

### ISSUE THREAD

**Issue by xulouzhe** [ExcitedCodes/URLOfOurOwn#6]
链接 https://ao3.org.cn/
采用该项目提供的nginx配置，关闭了disclaimer.html确认
但是文件还在，可以采用https://ao3.org.cn/disclaimer.html的链接访问

**Comment by ExcitedCodes** [comment]
抱歉, 这边项目是准备抛弃旧的设计思路了
简单的说, 应该不会再添加第三方的备用站点了

主要原因有两个
一是后期换成了边缘计算代理
二是愿意提交备用站点的人数太少，这边用户量太大(现在日活用户有 6000+ 了)，我怕分流到单个站点会直接造成该站的服务器被 AO3 屏蔽
